[package]
name = "griffin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stivale-boot = "0.2.1"
bitflags = "1.3.2"

[dependencies.lazy_static]
version = "1.4.0"
features = ["spin_no_std"]